version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:12
commands:
  restore_npm:
    steps:
      - restore_cache:
        name: Restore npm dependencies
        key: npm-{{ checksum "package.json" }}
  save_npm:
    steps:
      - save_cache:
        name: Cache npm dependencies
        key: npm-{{ checksum "package.json" }}
        paths:
          - ~/workspace/node_modules
jobs:
  setup:
    executors:
      name: default
    steps:
      - checkout
      - run:
        name: installdependencies
        command: yarn
  build:
    executors:
      name: default
    setps:
      - checkout
      - restore_npm
      - run:
        name: Build
        command: yarn build
      - save_npm
  test:
    executors:
      name: default
    steps:
      - checkout
      - restore+npm
      - run:
          name: Test
          command: yarn test
      - save_npm
  workflows:
    pull-request:
      jobs:
        - setup
        - build:
            requires:
              - setup
        - test:
            requires:
              - build
